"""Write the shell completion scripts from the parser itself.

Hand-written completions rot. A pass gets added, the completion keeps offering
the nine that existed when somebody last remembered, and the shell quietly
teaches the user that the new command does not exist. So these are generated
from `build_parser`, and a test regenerates them and fails on any difference,
which is the same discipline the golden files are under.

Run it after adding a command or a flag:

    python scripts/generate_completions.py
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from research_better.cli import PROGRAM, build_parser  # noqa: E402

TARGET = ROOT / "completions"

NAMES = (PROGRAM, "rb")
"""Both entry points. Somebody who types `rb` gets the same completion."""

HEADER = "# Generated by scripts/generate_completions.py. Do not edit."


@dataclass(frozen=True, slots=True)
class Command:
    name: str
    help: str
    flags: tuple[str, ...]


def _flags(parser: argparse.ArgumentParser) -> tuple[str, ...]:
    options: set[str] = set()
    for action in parser._actions:
        options.update(action.option_strings)
    return tuple(sorted(options))


def collect() -> tuple[tuple[Command, ...], tuple[str, ...]]:
    """Every subcommand with its own flags, and the flags the root takes."""
    parser = build_parser()
    subparsers = next(
        action for action in parser._actions if isinstance(action, argparse._SubParsersAction)
    )
    helps = {choice.dest: choice.help or "" for choice in subparsers._choices_actions}
    commands = tuple(
        Command(name=name, help=helps.get(name, ""), flags=_flags(sub))
        for name, sub in sorted(subparsers.choices.items())
    )
    return commands, _flags(parser)


def bash(commands: tuple[Command, ...], globals_: tuple[str, ...]) -> str:
    names = " ".join(command.name for command in commands)
    cases = "\n".join(
        f'        {command.name}) options="{" ".join(command.flags)}" ;;' for command in commands
    )
    return f"""{HEADER}
# Install: source this file, or drop it in /etc/bash_completion.d/

_research_better() {{
    local current previous command options
    current="${{COMP_WORDS[COMP_CWORD]}}"
    previous="${{COMP_WORDS[COMP_CWORD-1]}}"
    command=""

    local index
    for ((index = 1; index < COMP_CWORD; index++)); do
        case "${{COMP_WORDS[index]}}" in
            -*) ;;
            *) command="${{COMP_WORDS[index]}}"; break ;;
        esac
    done

    if [[ -z "$command" ]]; then
        COMPREPLY=($(compgen -W "{names} {" ".join(globals_)}" -- "$current"))
        return
    fi

    case "$previous" in
        --venue|--format) return ;;
    esac

    case "$command" in
{cases}
        *) options="" ;;
    esac

    if [[ "$current" == -* ]]; then
        COMPREPLY=($(compgen -W "$options" -- "$current"))
    else
        COMPREPLY=($(compgen -f -- "$current"))
    fi
}}

complete -F _research_better {" ".join(NAMES)}
"""


def zsh(commands: tuple[Command, ...], globals_: tuple[str, ...]) -> str:
    listed = "\n".join(
        f"        '{command.name}:{command.help.replace(chr(39), '')}'" for command in commands
    )
    cases = "\n".join(
        f"            {command.name})\n"
        f"                arguments=({' '.join(f'{flag!r}' for flag in command.flags)})\n"
        f"                ;;"
        for command in commands
    )
    return f"""#compdef {" ".join(NAMES)}
{HEADER}
# Install: put this file on $fpath as _research-better

_research_better() {{
    local -a commands arguments
    commands=(
{listed}
    )

    _arguments -C \\
        '1: :->command' \\
        '*: :->argument'

    case "$state" in
        command)
            _describe 'command' commands
            ;;
        argument)
            case "${{words[2]}}" in
{cases}
            esac
            _alternative \\
                "flags:flag:(${{arguments[*]}} {" ".join(globals_)})" \\
                'files:draft:_files'
            ;;
    esac
}}

_research_better "$@"
"""


def fish(commands: tuple[Command, ...], globals_: tuple[str, ...]) -> str:
    lines = [HEADER, "# Install: put this file in ~/.config/fish/completions/", ""]
    for name in NAMES:
        lines.append(f"complete -c {name} -f")
        for command in commands:
            described = command.help.replace("'", "")
            lines.append(
                f"complete -c {name} -n __fish_use_subcommand -a {command.name} -d '{described}'"
            )
        for command in commands:
            for flag in command.flags:
                if not flag.startswith("--"):
                    continue
                lines.append(
                    f"complete -c {name} -n '__fish_seen_subcommand_from {command.name}' "
                    f"-l {flag.lstrip('-')}"
                )
        lines.append(f"complete -c {name} -n __fish_use_subcommand -a '(__fish_complete_path)'")
        lines.append("")
    lines.append(f"# Root flags: {' '.join(globals_)}")
    lines.append("")
    return "\n".join(lines)


def render() -> dict[str, str]:
    commands, globals_ = collect()
    return {
        "research-better.bash": bash(commands, globals_),
        "research-better.zsh": zsh(commands, globals_),
        "research-better.fish": fish(commands, globals_),
    }


def main() -> int:
    TARGET.mkdir(exist_ok=True)
    for name, body in render().items():
        (TARGET / name).write_text(body, encoding="utf-8", newline="\n")
        print(f"wrote completions/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
