# Generated by scripts/generate_completions.py. Do not edit.
# Install: put this file in ~/.config/fish/completions/

complete -c research-better -f
complete -c research-better -n __fish_use_subcommand -a ask -d 'raise the questions a reviewer will ask'
complete -c research-better -n __fish_use_subcommand -a doctor -d 'report the installed version, the formats it can read, and what is missing'
complete -c research-better -n __fish_use_subcommand -a edit -d 'turn findings into a patch, applied only with --apply'
complete -c research-better -n __fish_use_subcommand -a findings -d 'print what the passes already found, without running anything'
complete -c research-better -n __fish_use_subcommand -a fluff -d 'find text that does not serve the papers argument'
complete -c research-better -n __fish_use_subcommand -a ground -d 'verify citations against the literature'
complete -c research-better -n __fish_use_subcommand -a ingest -d 'parse the draft and write its structure'
complete -c research-better -n __fish_use_subcommand -a novelty -d 'check that the body supports the stated contribution'
complete -c research-better -n __fish_use_subcommand -a originality -d 'unattributed overlap with work the tool can actually read'
complete -c research-better -n __fish_use_subcommand -a report -d 'one page of what was found and what could not be checked'
complete -c research-better -n __fish_use_subcommand -a revert -d 'restore the most recent backup of a draft'
complete -c research-better -n __fish_use_subcommand -a run -d 'every implemented pass, in order'
complete -c research-better -n __fish_use_subcommand -a trace -d 'passages that may read as machine-written, with the cause and the fix'
complete -c research-better -n __fish_use_subcommand -a voice -d 'profile how the author writes, so edits can be held to it'
complete -c research-better -n '__fish_seen_subcommand_from ask' -l format
complete -c research-better -n '__fish_seen_subcommand_from ask' -l help
complete -c research-better -n '__fish_seen_subcommand_from ask' -l json
complete -c research-better -n '__fish_seen_subcommand_from ask' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from ask' -l offline
complete -c research-better -n '__fish_seen_subcommand_from ask' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from ask' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from ask' -l venue
complete -c research-better -n '__fish_seen_subcommand_from ask' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from doctor' -l expect
complete -c research-better -n '__fish_seen_subcommand_from doctor' -l format
complete -c research-better -n '__fish_seen_subcommand_from doctor' -l help
complete -c research-better -n '__fish_seen_subcommand_from doctor' -l json
complete -c research-better -n '__fish_seen_subcommand_from doctor' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from doctor' -l offline
complete -c research-better -n '__fish_seen_subcommand_from doctor' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from doctor' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from doctor' -l venue
complete -c research-better -n '__fish_seen_subcommand_from doctor' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from edit' -l apply
complete -c research-better -n '__fish_seen_subcommand_from edit' -l force
complete -c research-better -n '__fish_seen_subcommand_from edit' -l format
complete -c research-better -n '__fish_seen_subcommand_from edit' -l help
complete -c research-better -n '__fish_seen_subcommand_from edit' -l interactive
complete -c research-better -n '__fish_seen_subcommand_from edit' -l json
complete -c research-better -n '__fish_seen_subcommand_from edit' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from edit' -l offline
complete -c research-better -n '__fish_seen_subcommand_from edit' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from edit' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from edit' -l target-reduction
complete -c research-better -n '__fish_seen_subcommand_from edit' -l venue
complete -c research-better -n '__fish_seen_subcommand_from edit' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from findings' -l format
complete -c research-better -n '__fish_seen_subcommand_from findings' -l help
complete -c research-better -n '__fish_seen_subcommand_from findings' -l json
complete -c research-better -n '__fish_seen_subcommand_from findings' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from findings' -l offline
complete -c research-better -n '__fish_seen_subcommand_from findings' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from findings' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from findings' -l venue
complete -c research-better -n '__fish_seen_subcommand_from findings' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from fluff' -l format
complete -c research-better -n '__fish_seen_subcommand_from fluff' -l help
complete -c research-better -n '__fish_seen_subcommand_from fluff' -l json
complete -c research-better -n '__fish_seen_subcommand_from fluff' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from fluff' -l offline
complete -c research-better -n '__fish_seen_subcommand_from fluff' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from fluff' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from fluff' -l venue
complete -c research-better -n '__fish_seen_subcommand_from fluff' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from ground' -l format
complete -c research-better -n '__fish_seen_subcommand_from ground' -l help
complete -c research-better -n '__fish_seen_subcommand_from ground' -l json
complete -c research-better -n '__fish_seen_subcommand_from ground' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from ground' -l offline
complete -c research-better -n '__fish_seen_subcommand_from ground' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from ground' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from ground' -l venue
complete -c research-better -n '__fish_seen_subcommand_from ground' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from ingest' -l format
complete -c research-better -n '__fish_seen_subcommand_from ingest' -l help
complete -c research-better -n '__fish_seen_subcommand_from ingest' -l json
complete -c research-better -n '__fish_seen_subcommand_from ingest' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from ingest' -l offline
complete -c research-better -n '__fish_seen_subcommand_from ingest' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from ingest' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from ingest' -l venue
complete -c research-better -n '__fish_seen_subcommand_from ingest' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from novelty' -l confirm-claim
complete -c research-better -n '__fish_seen_subcommand_from novelty' -l format
complete -c research-better -n '__fish_seen_subcommand_from novelty' -l help
complete -c research-better -n '__fish_seen_subcommand_from novelty' -l json
complete -c research-better -n '__fish_seen_subcommand_from novelty' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from novelty' -l offline
complete -c research-better -n '__fish_seen_subcommand_from novelty' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from novelty' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from novelty' -l venue
complete -c research-better -n '__fish_seen_subcommand_from novelty' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from originality' -l format
complete -c research-better -n '__fish_seen_subcommand_from originality' -l help
complete -c research-better -n '__fish_seen_subcommand_from originality' -l json
complete -c research-better -n '__fish_seen_subcommand_from originality' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from originality' -l offline
complete -c research-better -n '__fish_seen_subcommand_from originality' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from originality' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from originality' -l venue
complete -c research-better -n '__fish_seen_subcommand_from originality' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from report' -l check
complete -c research-better -n '__fish_seen_subcommand_from report' -l format
complete -c research-better -n '__fish_seen_subcommand_from report' -l help
complete -c research-better -n '__fish_seen_subcommand_from report' -l html
complete -c research-better -n '__fish_seen_subcommand_from report' -l json
complete -c research-better -n '__fish_seen_subcommand_from report' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from report' -l offline
complete -c research-better -n '__fish_seen_subcommand_from report' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from report' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from report' -l venue
complete -c research-better -n '__fish_seen_subcommand_from report' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from revert' -l format
complete -c research-better -n '__fish_seen_subcommand_from revert' -l help
complete -c research-better -n '__fish_seen_subcommand_from revert' -l json
complete -c research-better -n '__fish_seen_subcommand_from revert' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from revert' -l offline
complete -c research-better -n '__fish_seen_subcommand_from revert' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from revert' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from revert' -l venue
complete -c research-better -n '__fish_seen_subcommand_from revert' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from run' -l format
complete -c research-better -n '__fish_seen_subcommand_from run' -l help
complete -c research-better -n '__fish_seen_subcommand_from run' -l json
complete -c research-better -n '__fish_seen_subcommand_from run' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from run' -l offline
complete -c research-better -n '__fish_seen_subcommand_from run' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from run' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from run' -l venue
complete -c research-better -n '__fish_seen_subcommand_from run' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from trace' -l format
complete -c research-better -n '__fish_seen_subcommand_from trace' -l help
complete -c research-better -n '__fish_seen_subcommand_from trace' -l json
complete -c research-better -n '__fish_seen_subcommand_from trace' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from trace' -l offline
complete -c research-better -n '__fish_seen_subcommand_from trace' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from trace' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from trace' -l venue
complete -c research-better -n '__fish_seen_subcommand_from trace' -l verbose
complete -c research-better -n '__fish_seen_subcommand_from voice' -l format
complete -c research-better -n '__fish_seen_subcommand_from voice' -l help
complete -c research-better -n '__fish_seen_subcommand_from voice' -l json
complete -c research-better -n '__fish_seen_subcommand_from voice' -l no-color
complete -c research-better -n '__fish_seen_subcommand_from voice' -l offline
complete -c research-better -n '__fish_seen_subcommand_from voice' -l quiet
complete -c research-better -n '__fish_seen_subcommand_from voice' -l refresh
complete -c research-better -n '__fish_seen_subcommand_from voice' -l venue
complete -c research-better -n '__fish_seen_subcommand_from voice' -l verbose
complete -c research-better -n __fish_use_subcommand -a '(__fish_complete_path)'

complete -c rb -f
complete -c rb -n __fish_use_subcommand -a ask -d 'raise the questions a reviewer will ask'
complete -c rb -n __fish_use_subcommand -a doctor -d 'report the installed version, the formats it can read, and what is missing'
complete -c rb -n __fish_use_subcommand -a edit -d 'turn findings into a patch, applied only with --apply'
complete -c rb -n __fish_use_subcommand -a findings -d 'print what the passes already found, without running anything'
complete -c rb -n __fish_use_subcommand -a fluff -d 'find text that does not serve the papers argument'
complete -c rb -n __fish_use_subcommand -a ground -d 'verify citations against the literature'
complete -c rb -n __fish_use_subcommand -a ingest -d 'parse the draft and write its structure'
complete -c rb -n __fish_use_subcommand -a novelty -d 'check that the body supports the stated contribution'
complete -c rb -n __fish_use_subcommand -a originality -d 'unattributed overlap with work the tool can actually read'
complete -c rb -n __fish_use_subcommand -a report -d 'one page of what was found and what could not be checked'
complete -c rb -n __fish_use_subcommand -a revert -d 'restore the most recent backup of a draft'
complete -c rb -n __fish_use_subcommand -a run -d 'every implemented pass, in order'
complete -c rb -n __fish_use_subcommand -a trace -d 'passages that may read as machine-written, with the cause and the fix'
complete -c rb -n __fish_use_subcommand -a voice -d 'profile how the author writes, so edits can be held to it'
complete -c rb -n '__fish_seen_subcommand_from ask' -l format
complete -c rb -n '__fish_seen_subcommand_from ask' -l help
complete -c rb -n '__fish_seen_subcommand_from ask' -l json
complete -c rb -n '__fish_seen_subcommand_from ask' -l no-color
complete -c rb -n '__fish_seen_subcommand_from ask' -l offline
complete -c rb -n '__fish_seen_subcommand_from ask' -l quiet
complete -c rb -n '__fish_seen_subcommand_from ask' -l refresh
complete -c rb -n '__fish_seen_subcommand_from ask' -l venue
complete -c rb -n '__fish_seen_subcommand_from ask' -l verbose
complete -c rb -n '__fish_seen_subcommand_from doctor' -l expect
complete -c rb -n '__fish_seen_subcommand_from doctor' -l format
complete -c rb -n '__fish_seen_subcommand_from doctor' -l help
complete -c rb -n '__fish_seen_subcommand_from doctor' -l json
complete -c rb -n '__fish_seen_subcommand_from doctor' -l no-color
complete -c rb -n '__fish_seen_subcommand_from doctor' -l offline
complete -c rb -n '__fish_seen_subcommand_from doctor' -l quiet
complete -c rb -n '__fish_seen_subcommand_from doctor' -l refresh
complete -c rb -n '__fish_seen_subcommand_from doctor' -l venue
complete -c rb -n '__fish_seen_subcommand_from doctor' -l verbose
complete -c rb -n '__fish_seen_subcommand_from edit' -l apply
complete -c rb -n '__fish_seen_subcommand_from edit' -l force
complete -c rb -n '__fish_seen_subcommand_from edit' -l format
complete -c rb -n '__fish_seen_subcommand_from edit' -l help
complete -c rb -n '__fish_seen_subcommand_from edit' -l interactive
complete -c rb -n '__fish_seen_subcommand_from edit' -l json
complete -c rb -n '__fish_seen_subcommand_from edit' -l no-color
complete -c rb -n '__fish_seen_subcommand_from edit' -l offline
complete -c rb -n '__fish_seen_subcommand_from edit' -l quiet
complete -c rb -n '__fish_seen_subcommand_from edit' -l refresh
complete -c rb -n '__fish_seen_subcommand_from edit' -l target-reduction
complete -c rb -n '__fish_seen_subcommand_from edit' -l venue
complete -c rb -n '__fish_seen_subcommand_from edit' -l verbose
complete -c rb -n '__fish_seen_subcommand_from findings' -l format
complete -c rb -n '__fish_seen_subcommand_from findings' -l help
complete -c rb -n '__fish_seen_subcommand_from findings' -l json
complete -c rb -n '__fish_seen_subcommand_from findings' -l no-color
complete -c rb -n '__fish_seen_subcommand_from findings' -l offline
complete -c rb -n '__fish_seen_subcommand_from findings' -l quiet
complete -c rb -n '__fish_seen_subcommand_from findings' -l refresh
complete -c rb -n '__fish_seen_subcommand_from findings' -l venue
complete -c rb -n '__fish_seen_subcommand_from findings' -l verbose
complete -c rb -n '__fish_seen_subcommand_from fluff' -l format
complete -c rb -n '__fish_seen_subcommand_from fluff' -l help
complete -c rb -n '__fish_seen_subcommand_from fluff' -l json
complete -c rb -n '__fish_seen_subcommand_from fluff' -l no-color
complete -c rb -n '__fish_seen_subcommand_from fluff' -l offline
complete -c rb -n '__fish_seen_subcommand_from fluff' -l quiet
complete -c rb -n '__fish_seen_subcommand_from fluff' -l refresh
complete -c rb -n '__fish_seen_subcommand_from fluff' -l venue
complete -c rb -n '__fish_seen_subcommand_from fluff' -l verbose
complete -c rb -n '__fish_seen_subcommand_from ground' -l format
complete -c rb -n '__fish_seen_subcommand_from ground' -l help
complete -c rb -n '__fish_seen_subcommand_from ground' -l json
complete -c rb -n '__fish_seen_subcommand_from ground' -l no-color
complete -c rb -n '__fish_seen_subcommand_from ground' -l offline
complete -c rb -n '__fish_seen_subcommand_from ground' -l quiet
complete -c rb -n '__fish_seen_subcommand_from ground' -l refresh
complete -c rb -n '__fish_seen_subcommand_from ground' -l venue
complete -c rb -n '__fish_seen_subcommand_from ground' -l verbose
complete -c rb -n '__fish_seen_subcommand_from ingest' -l format
complete -c rb -n '__fish_seen_subcommand_from ingest' -l help
complete -c rb -n '__fish_seen_subcommand_from ingest' -l json
complete -c rb -n '__fish_seen_subcommand_from ingest' -l no-color
complete -c rb -n '__fish_seen_subcommand_from ingest' -l offline
complete -c rb -n '__fish_seen_subcommand_from ingest' -l quiet
complete -c rb -n '__fish_seen_subcommand_from ingest' -l refresh
complete -c rb -n '__fish_seen_subcommand_from ingest' -l venue
complete -c rb -n '__fish_seen_subcommand_from ingest' -l verbose
complete -c rb -n '__fish_seen_subcommand_from novelty' -l confirm-claim
complete -c rb -n '__fish_seen_subcommand_from novelty' -l format
complete -c rb -n '__fish_seen_subcommand_from novelty' -l help
complete -c rb -n '__fish_seen_subcommand_from novelty' -l json
complete -c rb -n '__fish_seen_subcommand_from novelty' -l no-color
complete -c rb -n '__fish_seen_subcommand_from novelty' -l offline
complete -c rb -n '__fish_seen_subcommand_from novelty' -l quiet
complete -c rb -n '__fish_seen_subcommand_from novelty' -l refresh
complete -c rb -n '__fish_seen_subcommand_from novelty' -l venue
complete -c rb -n '__fish_seen_subcommand_from novelty' -l verbose
complete -c rb -n '__fish_seen_subcommand_from originality' -l format
complete -c rb -n '__fish_seen_subcommand_from originality' -l help
complete -c rb -n '__fish_seen_subcommand_from originality' -l json
complete -c rb -n '__fish_seen_subcommand_from originality' -l no-color
complete -c rb -n '__fish_seen_subcommand_from originality' -l offline
complete -c rb -n '__fish_seen_subcommand_from originality' -l quiet
complete -c rb -n '__fish_seen_subcommand_from originality' -l refresh
complete -c rb -n '__fish_seen_subcommand_from originality' -l venue
complete -c rb -n '__fish_seen_subcommand_from originality' -l verbose
complete -c rb -n '__fish_seen_subcommand_from report' -l check
complete -c rb -n '__fish_seen_subcommand_from report' -l format
complete -c rb -n '__fish_seen_subcommand_from report' -l help
complete -c rb -n '__fish_seen_subcommand_from report' -l html
complete -c rb -n '__fish_seen_subcommand_from report' -l json
complete -c rb -n '__fish_seen_subcommand_from report' -l no-color
complete -c rb -n '__fish_seen_subcommand_from report' -l offline
complete -c rb -n '__fish_seen_subcommand_from report' -l quiet
complete -c rb -n '__fish_seen_subcommand_from report' -l refresh
complete -c rb -n '__fish_seen_subcommand_from report' -l venue
complete -c rb -n '__fish_seen_subcommand_from report' -l verbose
complete -c rb -n '__fish_seen_subcommand_from revert' -l format
complete -c rb -n '__fish_seen_subcommand_from revert' -l help
complete -c rb -n '__fish_seen_subcommand_from revert' -l json
complete -c rb -n '__fish_seen_subcommand_from revert' -l no-color
complete -c rb -n '__fish_seen_subcommand_from revert' -l offline
complete -c rb -n '__fish_seen_subcommand_from revert' -l quiet
complete -c rb -n '__fish_seen_subcommand_from revert' -l refresh
complete -c rb -n '__fish_seen_subcommand_from revert' -l venue
complete -c rb -n '__fish_seen_subcommand_from revert' -l verbose
complete -c rb -n '__fish_seen_subcommand_from run' -l format
complete -c rb -n '__fish_seen_subcommand_from run' -l help
complete -c rb -n '__fish_seen_subcommand_from run' -l json
complete -c rb -n '__fish_seen_subcommand_from run' -l no-color
complete -c rb -n '__fish_seen_subcommand_from run' -l offline
complete -c rb -n '__fish_seen_subcommand_from run' -l quiet
complete -c rb -n '__fish_seen_subcommand_from run' -l refresh
complete -c rb -n '__fish_seen_subcommand_from run' -l venue
complete -c rb -n '__fish_seen_subcommand_from run' -l verbose
complete -c rb -n '__fish_seen_subcommand_from trace' -l format
complete -c rb -n '__fish_seen_subcommand_from trace' -l help
complete -c rb -n '__fish_seen_subcommand_from trace' -l json
complete -c rb -n '__fish_seen_subcommand_from trace' -l no-color
complete -c rb -n '__fish_seen_subcommand_from trace' -l offline
complete -c rb -n '__fish_seen_subcommand_from trace' -l quiet
complete -c rb -n '__fish_seen_subcommand_from trace' -l refresh
complete -c rb -n '__fish_seen_subcommand_from trace' -l venue
complete -c rb -n '__fish_seen_subcommand_from trace' -l verbose
complete -c rb -n '__fish_seen_subcommand_from voice' -l format
complete -c rb -n '__fish_seen_subcommand_from voice' -l help
complete -c rb -n '__fish_seen_subcommand_from voice' -l json
complete -c rb -n '__fish_seen_subcommand_from voice' -l no-color
complete -c rb -n '__fish_seen_subcommand_from voice' -l offline
complete -c rb -n '__fish_seen_subcommand_from voice' -l quiet
complete -c rb -n '__fish_seen_subcommand_from voice' -l refresh
complete -c rb -n '__fish_seen_subcommand_from voice' -l venue
complete -c rb -n '__fish_seen_subcommand_from voice' -l verbose
complete -c rb -n __fish_use_subcommand -a '(__fish_complete_path)'

# Root flags: --format --help --json --no-color --offline --quiet --refresh --venue --verbose --version -h -q -v
