# Generated by scripts/generate_completions.py. Do not edit.
# Install: source this file, or drop it in /etc/bash_completion.d/

_research_better() {
    local current previous command options
    current="${COMP_WORDS[COMP_CWORD]}"
    previous="${COMP_WORDS[COMP_CWORD-1]}"
    command=""

    local index
    for ((index = 1; index < COMP_CWORD; index++)); do
        case "${COMP_WORDS[index]}" in
            -*) ;;
            *) command="${COMP_WORDS[index]}"; break ;;
        esac
    done

    if [[ -z "$command" ]]; then
        COMPREPLY=($(compgen -W "ask doctor edit findings fluff ground ingest novelty originality report revert run trace voice --format --help --json --no-color --offline --quiet --refresh --venue --verbose --version -h -q -v" -- "$current"))
        return
    fi

    case "$previous" in
        --venue|--format) return ;;
    esac

    case "$command" in
        ask) options="--format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        doctor) options="--expect --format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        edit) options="--apply --force --format --help --interactive --json --no-color --offline --quiet --refresh --target-reduction --venue --verbose -h -q -v" ;;
        findings) options="--format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        fluff) options="--format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        ground) options="--format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        ingest) options="--format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        novelty) options="--confirm-claim --format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        originality) options="--format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        report) options="--check --format --help --html --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        revert) options="--format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        run) options="--format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        trace) options="--format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        voice) options="--format --help --json --no-color --offline --quiet --refresh --venue --verbose -h -q -v" ;;
        *) options="" ;;
    esac

    if [[ "$current" == -* ]]; then
        COMPREPLY=($(compgen -W "$options" -- "$current"))
    else
        COMPREPLY=($(compgen -f -- "$current"))
    fi
}

complete -F _research_better research-better rb
