#compdef research-better rb
# Generated by scripts/generate_completions.py. Do not edit.
# Install: put this file on $fpath as _research-better

_research_better() {
    local -a commands arguments
    commands=(
        'ask:raise the questions a reviewer will ask'
        'doctor:report the installed version, the formats it can read, and what is missing'
        'edit:turn findings into a patch, applied only with --apply'
        'findings:print what the passes already found, without running anything'
        'fluff:find text that does not serve the papers argument'
        'ground:verify citations against the literature'
        'ingest:parse the draft and write its structure'
        'novelty:check that the body supports the stated contribution'
        'originality:unattributed overlap with work the tool can actually read'
        'report:one page of what was found and what could not be checked'
        'revert:restore the most recent backup of a draft'
        'run:every implemented pass, in order'
        'trace:passages that may read as machine-written, with the cause and the fix'
        'voice:profile how the author writes, so edits can be held to it'
    )

    _arguments -C \
        '1: :->command' \
        '*: :->argument'

    case "$state" in
        command)
            _describe 'command' commands
            ;;
        argument)
            case "${words[2]}" in
            ask)
                arguments=('--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            doctor)
                arguments=('--expect' '--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            edit)
                arguments=('--apply' '--force' '--format' '--help' '--interactive' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--target-reduction' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            findings)
                arguments=('--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            fluff)
                arguments=('--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            ground)
                arguments=('--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            ingest)
                arguments=('--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            novelty)
                arguments=('--confirm-claim' '--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            originality)
                arguments=('--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            report)
                arguments=('--check' '--format' '--help' '--html' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            revert)
                arguments=('--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            run)
                arguments=('--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            trace)
                arguments=('--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            voice)
                arguments=('--format' '--help' '--json' '--no-color' '--offline' '--quiet' '--refresh' '--venue' '--verbose' '-h' '-q' '-v')
                ;;
            esac
            _alternative \
                "flags:flag:(${arguments[*]} --format --help --json --no-color --offline --quiet --refresh --venue --verbose --version -h -q -v)" \
                'files:draft:_files'
            ;;
    esac
}

_research_better "$@"
